# Generated by Django 5.2.11 on 2026-03-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_ai_processing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobconfig',
            name='last_source_sent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
