# Generated by Django 5.2.11 on 2026-03-18 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0008_article_is_ai_processing_jobconfig_last_source_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='system_prompt',
            field=models.TextField(blank=True, help_text='Custom System Prompt for this team', null=True),
        ),
        migrations.AlterField(
            model_name='ailog',
            name='status',
            field=models.CharField(choices=[('success', 'Thnh cng'), ('error', 'Li')], default='success', max_length=20),
        ),
        migrations.AlterField(
            model_name='fetchlog',
            name='status',
            field=models.CharField(choices=[('success', 'Thnh cng'), ('error', 'Li'), ('partial', 'Mt phn')], max_length=10),
        ),
        migrations.AlterField(
            model_name='jobconfig',
            name='job_type',
            field=models.CharField(choices=[('crawl', 'Co d liu'), ('openrouter', 'Gi OpenRouter')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='force_collect',
            field=models.BooleanField(default=False, help_text='Bt  lun thu thp ngun ny, b qua thi gian ch'),
        ),
        migrations.AlterField(
            model_name='source',
            name='type',
            field=models.CharField(choices=[('api', 'API Endpoint'), ('rss', 'RSS Feed'), ('static', 'Web Tnh (AgentQL)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='description',
            field=models.TextField(blank=True, help_text='M t v cu hnh'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='key',
            field=models.CharField(choices=[('openrouter_api_key', 'OpenRouter API Key'), ('teams_webhook', 'Teams Webhook URL'), ('agentql_api_key', 'AgentQL API Key'), ('telegram_chat_id', 'Telegram Chat ID (Per Team)')], help_text='Chn loi cu hnh cn thit lp', max_length=100),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Chn team (ch p dng cho Teams Webhook)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configs', to='collector.team'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='value',
            field=models.TextField(help_text='Nhp gi tr cu hnh (API key hoc webhook URL)'),
        ),
        migrations.AlterField(
            model_name='team',
            name='code',
            field=models.CharField(help_text='M code ca team (v d: dev, ba, system)', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, help_text='M t v team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(help_text='Tn y  ca team', max_length=100),
        ),
    ]
