server {
    listen 80;
    server_name isdnews.telehub.vn;

    location = /favicon.ico { access_log off; log_not_found off; }

    location /static/ {
        alias /home/khiemtv/sources/isdnews/staticfiles/;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/home/khiemtv/sources/isdnews/isdnews.sock;
    }
}
